# Generated by Django 6.0.1 on 2026-02-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collages',
            old_name='name',
            new_name='Collage_name',
        ),
        migrations.RemoveField(
            model_name='collages',
            name='age',
        ),
        migrations.RemoveField(
            model_name='collages',
            name='enrollment_date',
        ),
        migrations.AddField(
            model_name='collages',
            name='Address',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collages',
            name='Collage_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collages',
            name='Fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collages',
            name='Total_Students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collages',
            name='Total_Teachers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
