# Generated by Django 6.0.1 on 2026-02-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_rename_name_collages_collage_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collages',
            old_name='Collage_id',
            new_name='Collages_id',
        ),
        migrations.RemoveField(
            model_name='collages',
            name='Collage_name',
        ),
        migrations.AddField(
            model_name='collages',
            name='Collages_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
