# Generated by Django 6.0.1 on 2026-02-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0003_rename_collage_id_collages_collages_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collages',
            old_name='Collages_id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='collages',
            old_name='Collages_name',
            new_name='_name',
        ),
    ]
