# Generated by Django 6.0.1 on 2026-02-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0004_rename_collages_id_collages__id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collages',
            old_name='_id',
            new_name='collage_id',
        ),
        migrations.RenameField(
            model_name='collages',
            old_name='_name',
            new_name='name',
        ),
    ]
