# Generated by Django 6.0.1 on 2026-02-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=100)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
