# Generated by Django 6.0.1 on 2026-02-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
