# Generated by Django 6.0.1 on 2026-02-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_shopping_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
