# Generated by Django 6.0.1 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
