# Generated by Django 6.0.1 on 2026-02-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='age',
            new_name='Esthablished',
        ),
        migrations.RemoveField(
            model_name='company',
            name='enrollment_date',
        ),
        migrations.AddField(
            model_name='company',
            name='GST',
            field=models.CharField(blank=True, null=True),
        ),
    ]
