# Generated by Django 6.0.1 on 2026-02-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_rename_age_company_esthablished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Co_Founder',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Founder',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Total_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
