# Generated by Django 6.0.1 on 2026-02-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('enrollment_date', models.DateField()),
                ('Address', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Teacher_id', models.IntegerField()),
                ('Collage_Name', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
