# Generated by Django 6.0.1 on 2026-02-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_teachers_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='Collage_Name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Gender',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Teacher_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
