# Generated by Django 6.0.1 on 2026-02-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_teachers_collage_name_alter_teachers_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='Address',
            field=models.CharField(blank=True, null=True),
        ),
    ]
