# Generated by Django 6.0.1 on 2026-02-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_teachers_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='Teacher_id',
            new_name='Teacher_Id',
        ),
    ]
