# Generated by Django 6.0.1 on 2026-02-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_teacher_id_teachers_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='Teacher_Id',
            new_name='Teachers_id',
        ),
    ]
