# Generated by Django 6.0.1 on 2026-02-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_teacher_id_teachers_teachers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='Teachers_id',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='enrollment_date',
        ),
    ]
