# Generated by Django 6.0.1 on 2026-02-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_teachers_teachers_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='Collage_Name',
        ),
    ]
