# Generated by Django 6.0.1 on 2026-02-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_teachers_collage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='Password',
            field=models.CharField(blank=True, null=True),
        ),
    ]
