# Generated by Django 6.0.1 on 2026-02-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articles_author_alter_articles_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image',
        ),
    ]
