# Generated by Django 6.0.1 on 2026-02-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='name',
            new_name='movie_name',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='age',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='enrollment_date',
        ),
        migrations.AddField(
            model_name='movies',
            name='Collection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='Hero',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='Realse_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
