# Generated by Django 6.0.1 on 2026-02-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_rename_name_movies_movie_name_remove_movies_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movie_budget',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='movie_name',
            new_name='name',
        ),
    ]
