# Generated by Django 6.0.1 on 2026-02-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='enrollment_date',
        ),
    ]
