# Generated by Django 6.0.1 on 2026-02-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_remove_students_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
