# Generated by Django 6.0.1 on 2026-02-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_students_enrollment_date_alter_students_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Address',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Collage_Name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Gender',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Students_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
